src/UnionArgParser/UnParsers.fs, src/UnionArgParser/UnionArgParser.fs
This is something we could make use of in fsprojects/Paket#514 when generating docs
=> Print command line syntax

src/UnionArgParser/ArgInfo.fs, src/UnionArgParser/Types.fs, tests/UnionArgParser.Tests/Tests.fs
Allows default args to have either double, single or no dash prefix. See #26.
=> Add support for PrefixAttribute.

src/Argu/ArgumentParser.fs, tests/Argu.Tests/Tests.fs
=> Usage without mandatory arguments should not raise an exception

src/Argu/ArgInfo.fs, src/Argu/Types.fs, tests/Argu.Tests/Tests.fs
removes the need to list `AltCommandLine` multiple times per union case
=> AltCommandLine can take array of alternatives

src/Argu/Attributes.fs, src/Argu/PreCompute.fs
This pull request adds the missing conventional `Attribute` suffix to the type name of the `GatherUnrecognized` attribute.
Because the suffix is optional when using an attribute, this is unproblematic for existing code that uses `GatherUnrecognized` normally. It would, however, break any code that references the type normally or accesses it via reflection, so this fix might not be applicable within this major version.
=> Add Attribute suffix to GatherUnrecognized type name

src/Argu.Core/Argu.Core.fsproj, src/Argu/ConfigReaders.fs, tests/Argu.Tests/Tests.fs
This addresses #95. I propose that Argu should take a dependency on `System.Configuration.ConfigurationManager` which would allow the removal of the conditional compilation directives, ergo bringing the behavior of Argu on different targets into alignment.
=> Support ConfigurationManager by default

.paket/Paket.Restore.targets, build.fsx, paket.dependencies, paket.lock, src/Argu.Core/paket.references, src/Argu/paket.references
This switches from source indexing to source linking by updating to SourceLink 2. This pull request is part of an effort to help us track down performance issues affecting Ionide by source linking all the pdb files used by it https://github.com/fsharp/FsAutoComplete/issues/264.
The NuGet package currently looks like this. The net40 is a Windows pdb that was being source indexed, but not the netstandard2.0 one. This pull request makes it so that netstandard2.0 is source linked, but not the net40 one. My recommendation is to change the net40 over to be a portable pdb and source link it as well. This can be done easily by switching the project to be a netcore project. This should be pretty easy since you already have one. I simply didn't want to make the change as part of this pull request. …
=> use SourceLink 2

src/Argu/PreCompute.fs, tests/Argu.Tests/Tests.fs
This was discovered on a Turkish Windows system. In this specific case, the capital I (in "Install") within the union would be ToLower'd into a Turkish dotless 'i'. This would cause the expected '--install' to not work correctly when passed on the commandline.
For the unit test added the global locale within the Thread is modified. A try/finally is used to help ensure that it is set back to the original locale. It is assumed that tests are not run in parallel.
=> Fixed incorrect commandline option generation in non-English locales

docs/content/perf.fsx, docs/content/tutorial.fsx, docs/tools/templates/template.cshtml, src/Argu/ArgumentParser.fs, src/Argu/ParseResults.fs, src/Argu/Parsers/Cli.fs, src/Argu/Parsers/Common.fs, src/Argu/Parsers/KeyValue.fs, src/Argu/PreCompute.fs, src/Argu/Types.fs, src/Argu/UnParsers.fs, src/Argu/UnionArgInfo.fs, src/Argu/Utils.fs
* Move lot of things to `Lazy<T>`
* Allow to bypass the checks that would force all theses lazy to materialize (Because the discriminated union structure is checked)
* Add a performance tips page to the docs
* Other small optimizations
**Note**: Some optimizations and additional fields (Like the addition of `GroupedSwitchRegex`) can seem to make no sense. They are here to pave the way for the next optimization that will allow to serialize the whole `UnionArgInfo` structure and loading it instead of computing it. The corresponding WIP branch can be found here : https://github.com/vbfox/Argu/tree/perf
=> Optionally bypass structure checks for performance

src/Argu/PreCompute.fs, src/Argu/Utils.fs
Here is another performance PR.
The main performance gain is the removal of repeated calls to `GetAttributes` and instead doing a single `GetAttributes` and reusing the values.
I also removed some usage of printf as building the printers take time and it's not very necessary here.
Performance looks like that:
| Method |              Args | BypassDependencyGraphChecks |     Mean |    Error |    StdDev |
|------- |------------------ |---------------------------- |---------:|---------:|----------:|
|  **Parse** | **add nuget Foo.Bar** |                       **False** | **323.0 ms** | **2.000 ms** |  **4.041 ms** |
|  **Parse** | **add nuget Foo.Bar** |                        **True** | **205.3 ms** | **3.239 ms** |  **6.543 ms** |
|  **Parse** |           **install** | …
=> Avoid attributes recomputation

src/Argu/PreCompute.fs, tests/Argu.Tests/Tests.fs
Allows the use of the original case of the Enum/DU as well as the lower-case-only.  e.g. 'Third' and 'third'.  (Of course, it also allows any case-mix as well -- e.g. 'tHird' -- but that seems acceptable.)
=> case-insensitivity for command-line enums

src/Argu/PreCompute.fs, src/Argu/Types.fs, src/Argu/Utils.fs
This chains the inner exceptions so that we see what types to add for reflection to work with CoreRT.
Before:
```
PS C:\Users\taggac\github\corert-fsharp-example> .\bin\Release\netcoreapp2.2\win-x64\native\littleClient.exe
Unhandled Exception: Argu.ArguException: Error generating usage string from IArgParserTemplate for case LsArguments.Block_Size.
at Argu.PreCompute.description@487-1.Invoke(String) + 0x34
at Argu.PreCompute.description@485.Invoke(Unit) + 0xc1
at System.Lazy`1.ViaFactory(LazyThreadSafetyMode) + 0xdd
at System.Lazy`1.ExecutionAndPublication(LazyHelper, Boolean) + 0x52
at System.Lazy`1.CreateValue() + 0x84
at Argu.PreCompute.postProcess@629.Invoke(UnionArgInfo.UnionArgInfo) + 0x301
at <StartupCode$Argu>.$ArgumentParser.-cctor@87-1.Invoke(Unit) + 0x5b
at …
```
=> chain exception from reflection

src/Argu/ParseResults.fs
I had problem when I added a subcommand case to `Arguments`. Because DU containing `ParseResults<_>` loses structural equality and comparison. I think comparing a `ParseResults<_>` by `GetAllResults` is a good idea.
* `Safer Code: Declaring Conditions for Equality over Container Types` in https://blogs.msdn.microsoft.com/dsyme/2009/11/08/equality-and-comparison-constraints-in-f/
=> WIP: Added equality and comparison to ParseResults<_>.

.paket/Paket.Restore.targets, src/Argu/Parsers/Cli.fs, tests/Argu.Tests/Tests.fs
This pull request fixes issue #132 .
The problem was really down to the way that the `MainCommand` mechanism interacts with the `ignoreUnrecognized` mechanism. The existing functionality is as follows. When a token is encountered that is not a named field, it is ajudged to be *unrecognized* or a parameter of a parameterised argument. The test for being an argument includes running the `MainCommand` parser against the token. If it succeeds, then that token is added as a parse result. Subsequently, the `MainCommand` arguments are tested for validity, for instance whether they appear in the `First` or `Last` positions, as specified by the MainCommand attributes. If these fail, then the parser returns an error.
If the `MainCommand` has type `string`, then all tokens become parseable. This …
=> Fix incorrect parsing of string-type MainCommands when ignoreUnrecognized=true

docs/content/tutorial.fsx
Just a small change to follow naming conventions for long abbreviations.
=> Rename type to match .NET naming conventions

docs/content/tutorial.fsx
Using "with" for augmentations isn't particularly normal convention (though it's pretty common)
My recommendation is to remove it and rely on alignmnent
=> Remove "with" to follow normal conventions

src/Argu/Parsers/Cli.fs, tests/Argu.Tests/Tests.fs
Didn't realise options were treated specially, have added a test which failed without the `Cli.fs` change, and passes with it. Do let me know if there's any other edge cases you think I might have missed :+1:.
=> `EqualsAssignmentOrSpaced` was broken with option types

docs/content/index.fsx
Currently the bottom of the page looks a little bit wonky, due to a small bracing error:
This should fix it.
=> Corrects index.fs.

src/Argu/PreCompute.fs, tests/Argu.Tests/Tests.fs
=> Numeric decimal separators are culture invariant

src/Argu/Parsers/Common.fs, tests/Argu.Tests/Tests.fs
I think that this fixes - https://github.com/fsprojects/Argu/issues/116   ?
I'm new to the project (and fairly new to F#) so I appreciate I might have missed something in the implementation.
=> Added post processing checking of sub command mandatory flag

Directory.Build.props
https://fsprojects.github.io/Argu/ is broken
and only 
http://fsprojects.github.io/Argu/
works
=> Fix website

Directory.Build.props, docs/index.fsx, docs/perf.fsx, samples/Argu.Samples.LS/Arguments.fs, src/Argu/ArgumentParser.fs, src/Argu/Attributes.fs, src/Argu/ConfigReaders.fs, src/Argu/ParseResults.fs, src/Argu/Parsers/Cli.fs, src/Argu/Parsers/Common.fs, src/Argu/Parsers/KeyValue.fs, src/Argu/PreCompute.fs, src/Argu/Types.fs, src/Argu/UnParsers.fs, src/Argu/UnionArgInfo.fs, src/Argu/Utils.fs, tests/Argu.Tests/Tests.fs, tests/Argu.Tests/tests.fsx
Warning level 5
fix typos
track lang changes (`__.`->`_.`, remove redundant `.` in `.[]` etc)
=> chore: Up to warning level 5

.github/dependabot.yml, .github/workflows/release.yml, RELEASE_NOTES.md
This is an attempt to perform a release via a manual dispatch action.
I'd like to start with just being able to run the release, we can improve some stuff in the future afterwards.
resolves #166
fixes #116 
fixes #159
=> Release 6.1.2

.github/workflows/release.yml
The git identity needs to be set in https://github.com/fsprojects/Argu/actions/runs/7181861887/job/19557118490
Because a commit is being pushed to the `gh-pages` branch.
=> chore: Set Git identity for gh-pages commits

samples/Argu.Samples.LS/Argu.Samples.LS.fsproj
Sets `IsPackable` to `false` for the LS sample
In order to inhibit production of a `.nupkg` for it (which the NuGet push action then proceeds to [attempt to] push)
re https://github.com/fsprojects/Argu/issues/189#issuecomment-1853681150
=> fix(Release): Inhibit packing of LS sample

RELEASE_NOTES.md, src/Argu/ParseResults.fs, tests/Argu.Tests/Tests.fs
Useful to defer computation work (or raising of an exception in the course of that) to look up a fallback where a parameter is missing
=> feat: Add GetResult(expr, defThunk)

RELEASE_NOTES.md, global.json, paket.dependencies, paket.lock, src/Argu/Argu.fsproj, src/Argu/paket.references
[Version 6.1.3](https://www.nuget.org/packages/Argu/6.1.3#dependencies-body-tab) has an incorrect additional reference
~Per https://github.com/fsprojects/Paket/issues/2951 this should remove that...~ Resolved by using a `PackageReference` rather than fighting `paket` on this one
=> fix: Remove incorrect Dotnet.ReproducibleBuilds ref

RELEASE_NOTES.md, src/Argu/Parsers/Cli.fs, src/Argu/Parsers/Common.fs, src/Argu/UnionArgInfo.fs, tests/Argu.Tests/Tests.fs
Here's a suggested correction for the regression in #127
resolves: #220
=> Fix mandatory parameters

RELEASE_NOTES.md, src/Argu/ArgumentParser.fs
Useful for including program name in other messages and/or as ids in filenames / consumer group names etc
=> feat(ArgumentParser): Expose ProgramName

RELEASE_NOTES.md, docs/index.fsx, docs/perf.fsx, docs/tutorial.fsx, src/Argu/ParseResults.fs, tests/Argu.Tests/Tests.fs
- Alias the 3 `*PostProcess*` functions as a `*GetResult*` (originals will be Obsoleted in V7, and removed in V8)
- Add 2 new overloads for defaulting `GetResult` that take a `parser` whose exceptions are trapped
resolves #211
=> feat(ParseResults): Add PostProcess->GetResult aliases

docs/index.fsx, tests/Argu.Tests/Tests.fs
I got tied up in knots suspecting a bug in Argu using locally installed `dotnet tool`s (I always install globally and hence it just works)
Invocation was
```
propulsion sync cosmos -s $EQUINOX_COSMOS_CONNECTION -d $EQUINOX_COSMOS_DATABASE -c $EQUINOX_COSMOS_CONTAINER  \
from cosmos -s $EQUINOX_COSMOS_CONNECTION -d sourcedb -c sourcecontainer
```
So I added naively added a `dotnet` before `toolname` to shut it up
Which resulted in a `ERROR: unrecognized argument: 'equinox-common-test'.` message
Which could only be fixed by replacing the two `-d` cases (which are `AltCommandLine` aliases) with the raw name (`--database`)
Hence this test, which proves nothing new, except that it's pretty naive to assume that Eirik left some wacky bugs in here!
Of course the actual problem is my stupidity, …
=> chore(Tests): Add learning/doc test re AltCommandLine `-d`

RELEASE_NOTES.md, src/Argu/ArgumentParser.fs, src/Argu/Utils.fs
When running via a wrapper such as `dotnet` or `dotnet tool run` (see https://github.com/fsprojects/Argu/pull/232 for more of the full scenario), the default logic derives the `programName` as `dotnet`, i.e. the exit error message becomes:
```
ERROR: unrecognized argument: 'equinox-common-test'.
USAGE: dotnet sync cosmos <snipped>
```
Another common case of this is that VS in ~2019 used to run in a wrapper, so the message would be correct if you Ctrl-F5 run, but not if you F5-run; who knows if that has changed...
=> fix(ArgumentParser): Correct default programName when run via wrapper

RELEASE_NOTES.md, src/Argu/Parsers/Cli.fs, src/Argu/Parsers/Common.fs, src/Argu/UnionArgInfo.fs, tests/Argu.Tests/Tests.fs
A regression has occurred in https://github.com/fsprojects/Argu/pull/127
Previously, if a case was missing, help was displayed for the subcommand and not for the main command. This was the same behaviour as when there was an unknown case.
This PR corrects this to restore the old behaviour.
At the same time, the error message when a case is missing has been improved. It used to display only the first missing case.
Now it displays all the missing cases.
=> fix(Mandatory args): list missing cases

RELEASE_NOTES.md, src/Argu/Attributes.fs
I've added `AttributeTargets.Method` to all attributes which have `AttributeTargets.Property`. I also added to obsolete attributes thinking it is necessary to avoid forcing removal of those attributes.
=> fixes #242: add missing attribute targets
